modeltype <- function(fit, ...)
  UseMethod("modeltype")
modeldata <- function(fit, ...)
  UseMethod("modeldata")
modelpars <- function(fit, ...)
  UseMethod("modelpars")
modelinfo <- function(fit, ...)
  UseMethod("modelinfo")

parnames.bm <- function()
  c("sigsq", "z0", "SE")
parnames.ou <- function()
  c("alpha", "sigsq", "z0", "SE")
parnames.eb <- function()
  c("a", "sigsq", "z0", "SE")
